# Generated by Django 4.2.30 on 2026-05-23 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('message_type', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=10)),
                ('audience', models.CharField(choices=[('SCHOOL', 'Entire School'), ('LEVEL', 'By Level'), ('CLASS', 'By Class (Level + Stream)'), ('INDIVIDUAL', 'Individual')], max_length=15)),
                ('target_level', models.CharField(blank=True, max_length=10)),
                ('target_stream', models.CharField(blank=True, max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_received', to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('whatsapp_url', models.URLField(blank=True, max_length=2000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communications.message')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
