# Generated by Django 4.2.30 on 2026-09-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_seed_sms_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsbatch',
            name='sender_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='sender_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
