# Generated by Django 4.2.30 on 2026-09-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_update_fee_reminder_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='whatsapp_url',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10),
        ),
    ]
