# Generated by Django 4.2.30 on 2026-07-24 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
