# Generated by Django 4.2.30 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('EXPELLED', 'Expelled')], db_index=True, default='ACTIVE', max_length=15),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['level', 'stream', 'status'], name='student_lvl_strm_stat_idx'),
        ),
    ]
