# Generated by Django 4.2.30 on 2026-09-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_delete_feestructure'),
        ('students', '0006_guardian_sms_opt_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N_BABY', 'Baby Class'), ('N_MIDDLE', 'Middle Class'), ('N_SENIOR', 'Senior Class'), ('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('stream', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('EXPELLED', 'Expelled')], max_length=15)),
                ('enrolled_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='fees.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year__year', 'level', 'stream'],
                'indexes': [models.Index(fields=['academic_year', 'level', 'stream', 'status'], name='enrolment_yr_lvl_strm_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='enrolment_student_year_uniq'),
        ),
    ]
