# Generated by Django 4.2.30 on 2026-09-24 10:51

from django.db import migrations, models
import students.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_seed_current_enrolments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='stream',
            field=students.fields.StreamField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=students.fields.StreamField(blank=True, max_length=10),
        ),
    ]
