# Generated by Django 4.2.30 on 2026-07-21 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0002_schoolcalendarevent'),
        ('students', '0001_initial'),
        ('staff', '0003_staffprofile_taught_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Boys'), ('F', 'Girls')], max_length=1)),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dormitories_managed', to='staff.staffprofile')),
            ],
            options={
                'verbose_name_plural': 'Dormitories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vacated_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_assignments', to='fees.academicyear')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='boarding.dormitory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_assignments', to='students.student')),
            ],
            options={
                'ordering': ['-is_active', 'dormitory__name', 'bed_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='boardingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'academic_year'), name='unique_active_boarding_assignment_per_year'),
        ),
    ]
