# Generated by Django 4.2.30 on 2026-09-25 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('PIVOT_TABLE', 'Pivot table'), ('COLUMN', 'Column chart'), ('STACKED_COLUMN', 'Stacked column chart'), ('BAR', 'Bar chart'), ('LINE', 'Line chart'), ('PIE', 'Pie chart'), ('SINGLE_VALUE', 'Single value')], max_length=20)),
                ('config', models.JSONField()),
                ('shared_with_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_visualizations', to=settings.AUTH_USER_MODEL)),
                ('pinned_by', models.ManyToManyField(blank=True, related_name='pinned_visualizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
