# Generated by Django 4.2.30 on 2026-05-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('fees', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('incident_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REFERRED', 'Referred to Headteacher'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10)),
                ('action_taken', models.TextField(blank=True)),
                ('referred_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to='staff.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_incidents', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('stream', models.CharField(max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to='fees.academicyear')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['academic_year', 'level', 'stream'],
                'unique_together': {('level', 'stream', 'academic_year')},
            },
        ),
    ]
