# Generated by Django 4.2.30 on 2026-05-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_disciplinaryincident_classteacherassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='taught_levels',
            field=models.JSONField(blank=True, default=list, help_text='Level groups: PRIMARY, OLEVEL, ALEVEL. Empty = all levels.'),
        ),
    ]
