# Generated by Django 4.2.30 on 2026-09-24 10:51

from django.db import migrations
import students.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_classteacherassignment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacherassignment',
            name='stream',
            field=students.fields.StreamField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='class_teacher_of_stream',
            field=students.fields.StreamField(blank=True, max_length=10),
        ),
    ]
