# Generated by Django 4.2.30 on 2026-05-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('q1_start', models.DateField(blank=True, null=True)),
                ('q1_end', models.DateField(blank=True, null=True)),
                ('q2_start', models.DateField(blank=True, null=True)),
                ('q2_end', models.DateField(blank=True, null=True)),
                ('q3_start', models.DateField(blank=True, null=True)),
                ('q3_end', models.DateField(blank=True, null=True)),
                ('q4_start', models.DateField(blank=True, null=True)),
                ('q4_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2')], max_length=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=5)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fees.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year__year', 'term', 'quarter', 'student__last_name'],
                'unique_together': {('student', 'academic_year', 'term', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('phone_used', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField()),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.invoice')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('term', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2')], max_length=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=5)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lunch_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activity_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='fees.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'level', 'term', 'quarter'],
                'unique_together': {('academic_year', 'level', 'term', 'quarter')},
            },
        ),
    ]
