# Generated by Django 4.2.30 on 2026-09-07 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_guardian_sms_opt_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0004_alter_feestructure_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DISCOUNT', 'Discount'), ('WAIVER', 'Waiver'), ('SCHOLARSHIP', 'Scholarship'), ('BURSARY', 'Bursary')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TUITION', 'Tuition'), ('TRANSPORT', 'Transport'), ('LUNCH', 'Lunch'), ('UNIFORM', 'Uniform'), ('ACTIVITY', 'Activity'), ('OTHER', 'Other')], max_length=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('level_snapshot', models.CharField(blank=True, choices=[('N_BABY', 'Baby Class'), ('N_MIDDLE', 'Middle Class'), ('N_SENIOR', 'Senior Class'), ('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('VOID', 'Void')], default='UNPAID', max_length=10)),
                ('source_kind', models.CharField(blank=True, max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_legacy', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['invoice', 'category'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('VOID_LINE', 'Voided charge'), ('PAYMENT_REVERSAL', 'Payment reversal'), ('MANUAL', 'Manual')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniformSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('ANNUAL', 'Annual fees'), ('QUARTERLY', 'Quarterly fees'), ('SALE', 'Sale')], default='QUARTERLY', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='fees.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Set on every payment; nullable only for the Phase 1 backfill window.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term',
            field=models.CharField(blank=True, choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARRIED_CREDIT', 'Carried Credit')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'ANNUAL')), fields=('student', 'academic_year'), name='uniq_annual_invoice_per_student_year'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'QUARTERLY')), fields=('student', 'academic_year', 'term', 'quarter'), name='uniq_quarterly_invoice_per_student_period'),
        ),
        migrations.AddField(
            model_name='uniformsaleitem',
            name='invoice_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='fees.invoiceline'),
        ),
        migrations.AddField(
            model_name='studentcredit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_credits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcredit',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_from_void', to='fees.invoiceline'),
        ),
        migrations.AddField(
            model_name='studentcredit',
            name='source_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_from_reversal', to='fees.payment'),
        ),
        migrations.AddField(
            model_name='studentcredit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_credits', to='students.student'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.invoiceline'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.payment'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fees.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeadjustment',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_adjustments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeadjustment',
            name='invoice_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='fees.invoiceline'),
        ),
        migrations.AddField(
            model_name='payment',
            name='funded_from_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consuming_payments', to='fees.studentcredit'),
        ),
        migrations.AddConstraint(
            model_name='studentcredit',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='studentcredit_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentcredit',
            constraint=models.CheckConstraint(check=models.Q(('remaining_amount__gte', 0)), name='studentcredit_remaining_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice_line'), name='uniq_alloc_per_payment_line'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sale', False), models.Q(('status', 'VOID'), _negated=True)), fields=('invoice', 'category'), name='uniq_standard_line_per_invoice_category'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='invoiceline_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='feeadjustment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='feeadjustment_amount_positive'),
        ),
    ]
