# Generated by Django 4.2.30 on 2026-09-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_backfill_fee_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N_BABY', 'Baby Class'), ('N_MIDDLE', 'Middle Class'), ('N_SENIOR', 'Senior Class'), ('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uniform_plans', to='fees.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'level'],
            },
        ),
        migrations.CreateModel(
            name='TuitionFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('LEVEL_GROUP', 'Level group'), ('LEVEL', 'Single class')], max_length=12)),
                ('level_group', models.CharField(blank=True, choices=[('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('OLEVEL', 'O-Level'), ('ALEVEL', 'A-Level')], max_length=10)),
                ('level', models.CharField(blank=True, choices=[('N_BABY', 'Baby Class'), ('N_MIDDLE', 'Middle Class'), ('N_SENIOR', 'Senior Class'), ('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_plans', to='fees.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'level_group', 'level'],
            },
        ),
        migrations.CreateModel(
            name='LunchFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2')], max_length=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=5)),
                ('day_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boarding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch_configs', to='fees.academicyear')),
            ],
            options={
                'ordering': ['-academic_year__year', 'term', 'quarter'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2')], max_length=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=5)),
                ('level', models.CharField(choices=[('N_BABY', 'Baby Class'), ('N_MIDDLE', 'Middle Class'), ('N_SENIOR', 'Senior Class'), ('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_plans', to='fees.academicyear')),
            ],
            options={
                'ordering': ['-academic_year__year', 'term', 'quarter', 'level'],
            },
        ),
        migrations.AddConstraint(
            model_name='uniformfeeplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('academic_year', 'level'), name='uniq_active_uniform_plan_per_level'),
        ),
        migrations.AddConstraint(
            model_name='tuitionfeeplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope', 'LEVEL_GROUP')), fields=('academic_year', 'level_group'), name='uniq_active_tuition_plan_per_group'),
        ),
        migrations.AddConstraint(
            model_name='tuitionfeeplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope', 'LEVEL')), fields=('academic_year', 'level'), name='uniq_active_tuition_plan_per_level'),
        ),
        migrations.AddConstraint(
            model_name='tuitionfeeplan',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('level', ''), ('level_group__gt', ''), ('scope', 'LEVEL_GROUP')), models.Q(('level__gt', ''), ('scope', 'LEVEL')), _connector='OR'), name='tuition_plan_scope_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='lunchfeeconfig',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term', 'quarter'), name='uniq_lunch_config_per_period'),
        ),
        migrations.AddConstraint(
            model_name='activityfeeplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('academic_year', 'term', 'quarter', 'level'), name='uniq_active_activity_plan_per_class_period'),
        ),
    ]
