# Generated by Django 4.2.30 on 2026-09-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_feestructure_to_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
