# Generated by Django 4.2.30 on 2026-09-24 10:06

from decimal import ROUND_DOWN, Decimal

from django.db import migrations, models


def split_existing_plans(apps, schema_editor):
    """Give every existing plan an equal quarterly split (remainder on Q4)."""
    TuitionFeePlan = apps.get_model('fees', 'TuitionFeePlan')
    for plan in TuitionFeePlan.objects.all():
        part = (plan.amount / 4).quantize(Decimal('1'), rounding=ROUND_DOWN)
        plan.q1_amount = plan.q2_amount = plan.q3_amount = part
        plan.q4_amount = plan.amount - 3 * part
        plan.save(update_fields=['q1_amount', 'q2_amount', 'q3_amount', 'q4_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_delete_feestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionfeeplan',
            name='q1_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tuitionfeeplan',
            name='q2_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tuitionfeeplan',
            name='q3_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tuitionfeeplan',
            name='q4_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(split_existing_plans, migrations.RunPython.noop),
    ]
