# Generated by Django 4.2.30 on 2026-09-24 10:51

from django.db import migrations
import students.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepackages', '0002_alter_homepackage_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepackage',
            name='stream',
            field=students.fields.StreamField(blank=True, max_length=10),
        ),
    ]
