# Generated by Django 4.2.30 on 2026-05-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner / Director'), ('HEADTEACHER', 'Headteacher'), ('ACADEMIC_TEACHER', 'Academic Teacher'), ('DISCIPLINE_TEACHER', 'Discipline Teacher'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], default='TEACHER', max_length=20),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('EXAM', 'Exam'), ('CLASS_ASSIGNMENT', 'Class Assignment'), ('DISCIPLINE', 'Discipline'), ('LEAVE', 'Leave'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
