# Generated by Django 4.2.30 on 2026-05-24 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Shule SMS School', max_length=255)),
                ('school_motto', models.CharField(blank=True, max_length=255)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('school_address', models.TextField(blank=True)),
                ('school_phone', models.CharField(blank=True, max_length=30)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('school_website', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('school_type', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('COMBINED', 'Combined (Primary + Secondary)')], default='COMBINED', max_length=10)),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner / Director'), ('SYSTEM_ADMIN', 'System Administrator'), ('HEADTEACHER', 'Headteacher'), ('ACADEMIC_TEACHER', 'Academic Teacher'), ('DISCIPLINE_TEACHER', 'Discipline Teacher'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], default='TEACHER', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('ROLE_CHANGED', 'Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('SETTINGS_UPDATED', 'Settings Updated'), ('SUBJECT_ADDED', 'Subject Added'), ('SUBJECT_UPDATED', 'Subject Updated'), ('SUBJECT_DELETED', 'Subject Deleted'), ('YEAR_CREATED', 'Academic Year Created'), ('YEAR_UPDATED', 'Academic Year Updated'), ('PASSWORD_RESET', 'Password Reset'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BULK_IMPORT', 'Bulk Import')], max_length=20)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
