# Generated by Django 4.2.30 on 2026-05-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schoolsettings_alter_user_role_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='active_levels',
            field=models.JSONField(blank=True, default=list, help_text='Level groups the school runs: PRIMARY, OLEVEL, ALEVEL'),
        ),
    ]
