# Generated by Django 4.2.30 on 2026-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner / Director'), ('SYSTEM_ADMIN', 'System Administrator'), ('HEADTEACHER', 'Headteacher'), ('ACADEMIC_TEACHER', 'Academic Teacher'), ('DISCIPLINE_TEACHER', 'Discipline Teacher'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('WARDEN', 'Warden'), ('LIBRARIAN', 'Librarian'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], default='TEACHER', max_length=20),
        ),
    ]
