# Generated by Django 4.2.30 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_deactivation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('ROLE_CHANGED', 'Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('SETTINGS_UPDATED', 'Settings Updated'), ('SUBJECT_ADDED', 'Subject Added'), ('SUBJECT_UPDATED', 'Subject Updated'), ('SUBJECT_DELETED', 'Subject Deleted'), ('YEAR_CREATED', 'Academic Year Created'), ('YEAR_UPDATED', 'Academic Year Updated'), ('PASSWORD_RESET', 'Password Reset'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BULK_IMPORT', 'Bulk Import'), ('ACCOUNT_LOCKED', 'Account Locked')], max_length=20),
        ),
    ]
