# Generated by Django 4.2.30 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('ROLE_CHANGED', 'Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('SETTINGS_UPDATED', 'Settings Updated'), ('SUBJECT_ADDED', 'Subject Added'), ('SUBJECT_UPDATED', 'Subject Updated'), ('SUBJECT_DELETED', 'Subject Deleted'), ('YEAR_CREATED', 'Academic Year Created'), ('YEAR_UPDATED', 'Academic Year Updated'), ('PASSWORD_RESET', 'Password Reset'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BULK_IMPORT', 'Bulk Import'), ('ACCOUNT_LOCKED', 'Account Locked')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner / Director'), ('SYSTEM_ADMIN', 'System Administrator'), ('HEADTEACHER', 'Headteacher'), ('ACADEMIC_TEACHER', 'Academic Teacher'), ('DISCIPLINE_TEACHER', 'Discipline Teacher'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('WARDEN', 'Warden'), ('LIBRARIAN', 'Librarian'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], db_index=True, default='TEACHER', max_length=20),
        ),
    ]
