# Generated by Django 4.2.30 on 2026-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_auditlog_action_alter_auditlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='active_levels',
            field=models.JSONField(blank=True, default=list, help_text='Level groups the school runs: NURSERY, PRIMARY, OLEVEL, ALEVEL'),
        ),
    ]
