# Generated by Django 4.2.30 on 2026-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_schoolsettings_active_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('ROLE_CHANGED', 'Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('SETTINGS_UPDATED', 'Settings Updated'), ('SUBJECT_ADDED', 'Subject Added'), ('SUBJECT_UPDATED', 'Subject Updated'), ('SUBJECT_DELETED', 'Subject Deleted'), ('STREAM_ADDED', 'Stream Added'), ('STREAM_UPDATED', 'Stream Updated'), ('STREAM_DELETED', 'Stream Deleted'), ('YEAR_CREATED', 'Academic Year Created'), ('YEAR_UPDATED', 'Academic Year Updated'), ('PASSWORD_RESET', 'Password Reset'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BULK_IMPORT', 'Bulk Import'), ('ACCOUNT_LOCKED', 'Account Locked')], db_index=True, max_length=20),
        ),
    ]
