# Generated by Django 4.2.30 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auditlog_analytics_drilldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='enabled_modules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('ROLE_CHANGED', 'Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('SETTINGS_UPDATED', 'Settings Updated'), ('SUBJECT_ADDED', 'Subject Added'), ('SUBJECT_UPDATED', 'Subject Updated'), ('SUBJECT_DELETED', 'Subject Deleted'), ('STREAM_ADDED', 'Stream Added'), ('STREAM_UPDATED', 'Stream Updated'), ('STREAM_DELETED', 'Stream Deleted'), ('YEAR_CREATED', 'Academic Year Created'), ('YEAR_UPDATED', 'Academic Year Updated'), ('PASSWORD_RESET', 'Password Reset'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BULK_IMPORT', 'Bulk Import'), ('ACCOUNT_LOCKED', 'Account Locked'), ('MODULES_UPDATED', 'Modules Updated'), ('ANALYTICS_DRILLDOWN', 'Analytics Pupil List Viewed')], db_index=True, max_length=20),
        ),
    ]
