# Generated by Django 4.2.30 on 2026-05-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2')], max_length=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=5)),
                ('level', models.CharField(choices=[('STD1', 'Standard 1'), ('STD2', 'Standard 2'), ('STD3', 'Standard 3'), ('STD4', 'Standard 4'), ('STD5', 'Standard 5'), ('STD6', 'Standard 6'), ('STD7', 'Standard 7'), ('FORM1', 'Form 1'), ('FORM2', 'Form 2'), ('FORM3', 'Form 3'), ('FORM4', 'Form 4'), ('FORM5', 'Form 5'), ('FORM6', 'Form 6')], max_length=10)),
                ('stream', models.CharField(blank=True, max_length=10)),
                ('exam_type', models.CharField(choices=[('CA1', 'Continuous Assessment 1'), ('CA2', 'Continuous Assessment 2'), ('MIDTERM', 'Mid-Term'), ('TERMINAL', 'Terminal'), ('MOCK', 'Mock')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-academic_year__year', 'term', 'quarter', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('level_group', models.CharField(choices=[('PRIMARY', 'Primary (Std 1-7)'), ('OLEVEL', 'O-Level (Form 1-4)'), ('ALEVEL', 'A-Level (Form 5-6)')], max_length=10)),
                ('is_compulsory', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_entries', to='exams.subject')),
            ],
            options={
                'ordering': ['student__last_name', 'subject__name'],
            },
        ),
    ]
