# Generated by Django 4.2.30 on 2026-08-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_level_alter_subject_level_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('CA1', 'Continuous Assessment 1'), ('CA2', 'Continuous Assessment 2'), ('WEEKLY', 'Weekly Test'), ('MIDTERM', 'Mid-Term'), ('TERMINAL', 'Terminal'), ('MOCK', 'Mock')], max_length=10),
        ),
    ]
