# Generated by Django 4.2.30 on 2026-09-18 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_guardian_sms_opt_out'),
        ('exams', '0005_alter_exam_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('CREATIVITY', 'Creativity'), ('DISCIPLINE', 'Discipline'), ('SPORT', 'Sport'), ('SMARTNESS', 'Smartness'), ('SPEAKING_SKILLS', 'Speaking Skills'), ('WRITING_SKILLS', 'Writing Skills')], max_length=20)),
                ('marks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_assessments_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='students.student')),
            ],
            options={
                'ordering': ['student__last_name', 'skill'],
                'unique_together': {('exam', 'student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ReportCardRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_text', models.TextField(blank=True)),
                ('class_teacher_name', models.CharField(blank=True, max_length=255)),
                ('class_teacher_date', models.DateField(blank=True, null=True)),
                ('class_teacher_signature', models.ImageField(blank=True, null=True, upload_to='report_signatures/')),
                ('academic_text', models.TextField(blank=True)),
                ('academic_name', models.CharField(blank=True, max_length=255)),
                ('academic_date', models.DateField(blank=True, null=True)),
                ('academic_signature', models.ImageField(blank=True, null=True, upload_to='report_signatures/')),
                ('head_teacher_text', models.TextField(blank=True)),
                ('head_teacher_date', models.DateField(blank=True, null=True)),
                ('head_teacher_signature', models.ImageField(blank=True, null=True, upload_to='report_signatures/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_remarks', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_remarks', to='students.student')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_remarks_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
