# Generated by Django 4.2.30 on 2026-09-24 10:51

from django.db import migrations
import students.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_studentskillassessment_reportcardremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='stream',
            field=students.fields.StreamField(blank=True, max_length=10),
        ),
    ]
