# Generated by Django 4.2.30 on 2026-07-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('TRANSFER_LETTER', 'Transfer Letter'), ('MEDICAL_FORM', 'Medical Form'), ('IMMUNIZATION_RECORD', 'Immunization Record'), ('NATIONAL_ID', 'National ID / Passport'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
