# Generated by Django 4.2.30 on 2026-07-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('teacher', 'academic_year', 'day_of_week', 'period'), name='unique_teacher_per_timeslot'),
        ),
    ]
